language: java
script: mvn clean verify

matrix:
  include:
    # Linux / Headed (AWT Robot)
    - os: linux
      jdk: openjdk11
      dist: trusty
      env:
        - _JAVA_OPTIONS="-Dtestfx.robot=awt"
    # Linux / Headed (Glass Robot) / HiDPI
    - os: linux
      jdk: openjdk11
      dist: trusty
      env:
        - _JAVA_OPTIONS="-Dtestfx.robot=glass -Dglass.gtk.uiScale=2.0"
    # Linux / Headless
    - os: linux
      jdk: openjdk11
      dist: trusty
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true